# This is a basic workflow to help you get started with Actions
name: First Workflow

# Controls when the workflow will run
on: workflow_dispatch

# Jobs definations
jobs:
   first-job:
      runs-on: ubuntu-latest
      steps:
         - name: Print greeting
           run: |
                 echo "Hello World!"
                 echo "Second Hello World!"
         - name: Print goodbye
           run: |
                 echo "Done - bye!"
                 echo "Second Done - Bye"
           
